name: main-on-dev Branch 🐧
run-name: ${{ github.actor }} main-on-dev 🚀
on:
  push:
    branches:
      - dev
jobs:
  main-on-dev-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Push on dev branch by a ${{ github.event_name }} event."
